@ECHO OFF

REM This script requires the following environment variables to be set:
REM 1. OPENTWIN_DEV_ROOT
REM 2. OPENTWIN_THIRDPARTY_ROOT
REM 3. DEVENV_ROOT_2022
IF "%OPENTWIN_DEV_ROOT%" == "" (
	ECHO Please specify the following environment variables: OPENTWIN_DEV_ROOT
	goto PAUSE_END
)

IF "%OPENTWIN_THIRDPARTY_ROOT%" == "" (
	ECHO Please specify the following environment variables: OPENTWIN_THIRDPARTY_ROOT
	goto PAUSE_END
)

IF "%DEVENV_ROOT_2022%" == "" (
	ECHO Please specify the following environment variables: DEVENV_ROOT_2022
	goto PAUSE_END
)

REM Setup eviroment
CALL "%OPENTWIN_DEV_ROOT%\Scripts\SetupEnvironment.bat"

REM Ensure that the script finished successfully
IF NOT "%OPENTWIN_DEV_ENV_DEFINED%" == "1" (
	goto END
)

SET OPENTWIN_FRONTEND_DEPLOYMENT=%OPENTWIN_DEV_ROOT%\Deployment_Frontend

REM Clean up the Deployment directory

RMDIR /S /Q "%OPENTWIN_FRONTEND_DEPLOYMENT%"
MKDIR "%OPENTWIN_FRONTEND_DEPLOYMENT%"

RMDIR /S /Q "%OPENTWIN_DEV_ROOT%\Deployment\FrontendInstaller"
MKDIR "%OPENTWIN_DEV_ROOT%\Deployment\FrontendInstaller"

REM ===========================================================================
REM Copy the library files
REM ===========================================================================

REM Qwt
COPY "%QWT_LIB_DLLR%\qwt.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QWTPOLAR_LIB_DLLR%\qwtpolar.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"

REM QtTabToolbar
COPY "%QT_TT_DLLR%\TabToolbar.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"

REM Qt AdvancedDockingSystem
COPY "%QT_ADS_ROOT%\lib\qtadvanceddocking.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"

REM OpenSceneGraph
COPY "%OSG_DLLR%\*.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
MKDIR "%OPENTWIN_FRONTEND_DEPLOYMENT%\osgPlugins-3.6.3"
XCOPY /S "%OSG_DLLR%\osgPlugins-3.6.3" "%OPENTWIN_FRONTEND_DEPLOYMENT%\osgPlugins-3.6.3"

REM Fonts
MKDIR "%OPENTWIN_FRONTEND_DEPLOYMENT%\fonts"
XCOPY /S "%OPENTWIN_DEV_ROOT%\Assets\Fonts" "%OPENTWIN_FRONTEND_DEPLOYMENT%\fonts"

REM OpenGL Software Rendering
COPY "%OPENTWIN_THIRDPARTY_ROOT%\MesaOpenGL\*.*" "%OPENTWIN_FRONTEND_DEPLOYMENT%"

REM Qt
REM COPY "%QT_DLLR%\libEGL.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
REM COPY "%QT_DLLR%\libGLESv2.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
REM COPY "%QT_DLLR%\opengl32sw.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt63DAnimation.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt63DCore.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt63DExtras.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt63DInput.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt63DLogic.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt63DQuick.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt63DQuickAnimation.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt63DQuickExtras.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt63DQuickInput.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt63DQuickRender.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt63DQuickScene2D.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt63DRender.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Bluetooth.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Charts.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Concurrent.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Core.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6DataVisualization.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6DBus.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Gamepad.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Gui.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Help.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Location.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Multimedia.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6MultimediaQuick.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6MultimediaWidgets.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Network.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6NetworkAuth.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Nfc.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6OpenGL.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6OpenGLWidgets.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Positioning.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6PositioningQuick.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6PrintSupport.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Purchasing.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Qml.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Quick.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6QuickControls2.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6QuickParticles.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6QuickTemplates2.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6QuickTest.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6QuickWidgets.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6RemoteObjects.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Script.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6ScriptTools.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Scxml.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Sensors.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6SerialBus.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6SerialPort.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Sql.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Svg.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Test.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6TextToSpeech.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6WebChannel.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6WebEngine.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6WebEngineCore.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6WebEngineWidgets.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6WebSockets.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6WebView.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Widgets.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6WinExtras.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6Xml.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%QT_DLLR%\Qt6XmlPatterns.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"

MKDIR "%OPENTWIN_FRONTEND_DEPLOYMENT%\plugins"
MKDIR "%OPENTWIN_FRONTEND_DEPLOYMENT%\plugins\imageformats"
MKDIR "%OPENTWIN_FRONTEND_DEPLOYMENT%\plugins\platforms"
MKDIR "%OPENTWIN_FRONTEND_DEPLOYMENT%\plugins\renderers"
MKDIR "%OPENTWIN_FRONTEND_DEPLOYMENT%\plugins\rendererplugins"
MKDIR "%OPENTWIN_FRONTEND_DEPLOYMENT%\plugins\tls"
XCOPY /S "%QDIR%\plugins\imageformats" "%OPENTWIN_FRONTEND_DEPLOYMENT%\plugins\imageformats"
XCOPY /S "%QDIR%\plugins\platforms" "%OPENTWIN_FRONTEND_DEPLOYMENT%\plugins\platforms"
XCOPY /S "%QDIR%\plugins\renderers" "%OPENTWIN_FRONTEND_DEPLOYMENT%\plugins\renderers"
XCOPY /S "%QDIR%\plugins\rendererplugins" "%OPENTWIN_FRONTEND_DEPLOYMENT%\plugins\rendererplugins"
XCOPY /S "%QDIR%\plugins\tls" "%OPENTWIN_FRONTEND_DEPLOYMENT%\plugins\tls"

for /r "%OPENTWIN_FRONTEND_DEPLOYMENT%\plugins" %%f in (*.pdb) do (
    del "%%f"
)

REM Copy the OpenSSL libs for the Qt Websocket
COPY /Y "%OPENSSL_WEBSOCKET_DLLR%\*.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"

REM Copy the icons
MKDIR "%OPENTWIN_FRONTEND_DEPLOYMENT%\icons"
XCOPY /S "%OPENTWIN_DEV_ROOT%\Assets\Icons" "%OPENTWIN_FRONTEND_DEPLOYMENT%\icons"

REM CURL
COPY "%CURL_DLLR%\libcurl.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"

REM OPENSSL
COPY "%OPENSSL_DLL%\libcrypto-1_1-x64.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OPENSSL_DLL%\libssl-1_1-x64.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"

REM EMBREE
COPY "%EMBREE_BIN%\embree3.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%EMBREE_BIN%\tbb12.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"

REM MongoDB
COPY /Y "%MONGO_CXX_DLLR%\*.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY /Y "%MONGO_C_DLLR%\*.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"

REM ZLIB
COPY "%ZLIB_DLLPATHR%\zlib.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"

REM OpenCascade
COPY "%FMP_DLLR%\*.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%FRI_DLLR%\*.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%FRT_DLLR%\*.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OC_DLLR%\*.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%TBB_DLLR%\tbb.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%TBB_DLLR%\tbb_preview.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%TBB_DLLR%\tbbmalloc.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OVR_DLLR%\*.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%JEM_DLLR%\*.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"

REM ===========================================================================
REM Copy the build files
REM ===========================================================================

COPY "%OT_CORE_ROOT%\%OT_DLLR%\OTCore.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OT_RANDOM_ROOT%\%OT_DLLR%\OTRandom.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OT_SYSTEM_ROOT%\%OT_DLLR%\OTSystem.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OT_COMMUNICATION_ROOT%\%OT_DLLR%\OTCommunication.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OT_MODELENTITIES_ROOT%\%OT_DLLR%\ModelEntities.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OT_CADMODELENTITIES_ROOT%\%OT_DLLR%\CADModelEntities.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OT_VIEWER_ROOT%\%OT_DLLR%\Viewer.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OT_DATASTORAGE_ROOT%\%OT_DLLR%\DataStorage.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OT_UICORE_ROOT%\%OT_DLLR%\uiCore.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OT_RUBBERBANDAPI_ROOT%\%OT_DLLR%\RubberbandEngineCore.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OT_RUBBERBAND_ROOT%\%OT_DLLR%\RubberbandEngineOsgWrapper.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OT_QWTWRAPPER_ROOT%\%OT_DLLR%\QwtWrapper.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OT_GUI_ROOT%\%OT_DLLR%\OTGui.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OT_GUIAPI_ROOT%\%OT_DLLR%\OTGuiAPI.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OT_SCI_ROOT%\%OT_DLLR%\OTsci.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OT_WIDGETS_ROOT%\%OT_DLLR%\OTWidgets.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OT_STUDIO_SUITE_CONNECTOR_ROOT%\%OT_DLLR%\StudioSuiteConnector.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OT_BLOCKENTITIES_ROOT%\%OT_DLLR%\BlockEntities.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OT_UI_SERVICE_ROOT%\%OT_DLLR%\uiFrontend.exe" "%OPENTWIN_FRONTEND_DEPLOYMENT%"
COPY "%OT_FOUNDATION_ROOT%\%OT_DLLR%\OTServiceFoundation.dll" "%OPENTWIN_FRONTEND_DEPLOYMENT%"

REM  Copy Color Styles
MKDIR "%OPENTWIN_FRONTEND_DEPLOYMENT%\ColorStyles"
XCOPY /S "%OPENTWIN_DEV_ROOT%\Assets\ColorStyles" "%OPENTWIN_FRONTEND_DEPLOYMENT%\ColorStyles"

REM  Copy GraphicsItems
MKDIR "%OPENTWIN_FRONTEND_DEPLOYMENT%\GraphicsItems"
XCOPY /S "%OPENTWIN_DEV_ROOT%\Assets\GraphicsItems\*.ot.json" "%OPENTWIN_FRONTEND_DEPLOYMENT%\GraphicsItems"

REM Copy the certificates
MKDIR "%OPENTWIN_FRONTEND_DEPLOYMENT%\Certificates"
COPY "%OPENTWIN_DEV_ROOT%\Certificates\Generated\ca.pem" "%OPENTWIN_FRONTEND_DEPLOYMENT%\Certificates"
COPY "%OPENTWIN_DEV_ROOT%\Certificates\Generated\server.pem" "%OPENTWIN_FRONTEND_DEPLOYMENT%\Certificates"
COPY "%OPENTWIN_DEV_ROOT%\Certificates\Generated\server-key.pem" "%OPENTWIN_FRONTEND_DEPLOYMENT%\Certificates"

ECHO [Paths] > "%OPENTWIN_FRONTEND_DEPLOYMENT%\qt.conf"
ECHO Plugins = .\\plugins >> "%OPENTWIN_FRONTEND_DEPLOYMENT%\qt.conf"

REM ===========================================================================
REM Finally create the installer
REM ===========================================================================

REM CALL "C:\Program Files (x86)\NSIS\makensis.exe" Install-OpenTwin.nsi

REM MOVE "Install OpenTwin.exe" ..\Deployment\Frontend-Installer"

