// @otlicense
// File: UniqueUIDGenerator.h
// 
// License:
// Copyright 2025 by OpenTwin
//  
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// @otlicense-end

#pragma once

// OpenTwin header
#include "OTCore/CoreTypes.h"
#include "OTDataStorage/DataStorageAPIExport.h"

// std header
#include <mutex>
#include <time.h>
#include <cassert>

namespace ot
{

	//! @brief The UniqueUIDGenerator class generates unique UIDs based on the current time, session ID, service ID, and an internal counter.
	//! The generated UIDs are guaranteed to be unique across different sessions and services, as long as the session ID and service ID are unique.
	//! The class is thread-safe and will block if the maximum number of UIDs for the current second has been reached.
	class OT_DATASTORAGE_API_EXPORT UniqueUIDGenerator
	{
		OT_DECL_NOCOPY(UniqueUIDGenerator)
		OT_DECL_NOMOVE(UniqueUIDGenerator)
		OT_DECL_NODEFAULT(UniqueUIDGenerator)
	public:
		explicit UniqueUIDGenerator(unsigned int _sessionID, unsigned int _serviceID);
		
		//! @brief Generates a unique UID based on the current time, session ID, service ID, and an internal counter.
		//! This function is thread-safe and will block if the maximum number of UIDs for the current second has been reached.
		//! @return A unique UID.
		OT_DECL_NODISCARD ot::UID getUID();

	private:
		//! @brief Returns a reference to the mutex used for synchronizing UID generation across threads.
		static std::mutex& getGenerationLock();

		//! @brief Returns the current time in seconds since 2020.
		inline std::time_t getTimeSince2020()
		{
			constexpr std::time_t secondsTill2020 = 1577836800;
			return std::time(nullptr) - secondsTill2020;
		}

		static constexpr int c_timeBits = 36;     //! @brief Number of bits allocated for the time component of the UID.
		static constexpr int c_counterBits = 14;  //! @brief Number of bits allocated for the counter component of the UID.
		static constexpr int c_serviceIDBits = 8; //! @brief Number of bits allocated for the service ID component of the UID.
		static constexpr int c_sessionIDBits = 6; //! @brief Number of bits allocated for the session ID component of the UID.
		static_assert(c_timeBits + c_counterBits + c_serviceIDBits + c_sessionIDBits == (sizeof(UID) * 8), "UID bit allocation does not sum up to UID bit count");

		static constexpr int c_maxCounter   = (1 << c_counterBits)   - 1;  //! @brief Maximum value for the counter component of the UID.
		static constexpr int c_maxServiceID = (1 << c_serviceIDBits) - 1;  //! @brief Maximum value for the service ID component of the UID.
		static constexpr int c_maxSessionID = (1 << c_sessionIDBits) - 1;  //! @brief Maximum value for the session ID component of the UID.

		unsigned int m_counter   : c_counterBits;   //! @brief Internal counter to ensure uniqueness of UIDs generated within the same second.
		unsigned int m_serviceID : c_serviceIDBits; //! @brief Service ID to ensure uniqueness of UIDs generated by different services.
		unsigned int m_sessionID : c_sessionIDBits; //! @brief Session ID to ensure uniqueness of UIDs generated by different sessions.

		//! @brief The last time (in seconds since 2020) when a UID was generated.
		//! Used to reset the counter when the time changes.
		std::time_t m_lastTime;
	};
};
