# License:
# Copyright 2026 by OpenTwin
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Platform-specific additions live in opentwin/platform.py REQUIRED.
REQUIRED = ["OPENTWIN_DEV_ROOT", "OPENTWIN_THIRDPARTY_ROOT"]

# ===== Services =====
SERVICES = {
    "OT_AUTHORISATION_SERVICE_ROOT": "AuthorisationService",
    "OT_MODEL_SERVICE_ROOT": "Model",
    "OT_GLOBAL_SESSION_SERVICE_ROOT": "GlobalSessionService",
    "OT_LOCAL_SESSION_SERVICE_ROOT": "LocalSessionService",
    "OT_GLOBAL_DIRECTORY_SERVICE_ROOT": "GlobalDirectoryService",
    "OT_LOCAL_DIRECTORY_SERVICE_ROOT": "LocalDirectoryService",
    "OT_RELAY_SERVICE_ROOT": "RelayService",
    "OT_LOGGER_SERVICE_ROOT": "LoggerService",
    "OT_PHREEC_SERVICE_ROOT": "PHREECService",
    "OT_KRIGING_SERVICE_ROOT": "KrigingService",
    "OT_MODELING_SERVICE_ROOT": "ModelingService",
    "OT_VISUALIZATION_SERVICE_ROOT": "VisualizationService",
    "OT_FITTD_SERVICE_ROOT": "FITTDService",
    "OT_CARTESIAN_MESH_SERVICE_ROOT": "CartesianMeshService",
    "OT_TET_MESH_SERVICE_ROOT": "TetMeshService",
    "OT_IMPORT_PARAMETERIZED_DATA_SERVICE_ROOT": "ImportParameterizedData",
    "OT_GETDP_SERVICE_ROOT": "GetDPService",
    "OT_ELMERFEM_SERVICE_ROOT": "ElmerFEMService",
    "OT_STUDIOSUITE_SERVICE_ROOT": "StudioSuiteService",
    "OT_LTSPICE_SERVICE_ROOT": "LTSpiceService",
    "OT_UI_SERVICE_ROOT": "uiService",
    "OT_PYTHON_EXECUTION_SERVICE_ROOT": "PythonExecutionService",
    "OT_DATA_PROCESSING_SERVICE_ROOT": "DataProcessingService",
    "OT_CIRCUIT_SIMULATOR_SERVICE_ROOT": "CircuitSimulatorService",
    "OT_PYRIT_SERVICE_ROOT": "PyritService",
    "OT_OPENEMS_SERVICE_ROOT": "OpenEMSService",
    "OT_LIBRARY_MANAGEMENT_SERVICE_ROOT": "LibraryManagementService",
    "OT_HIERARCHICAL_PROJECT_SERVICE_ROOT": "HierarchicalProjectService",
    "OT_FILEMANAGEMENT_PROJECT_SERVICE_ROOT": "FileManagementProjectService",
    "OT_PYTHON_EXECUTION_ROOT": "PythonExecution",
    "OT_CIRCUIT_EXECUTION_ROOT": "CircuitExecution",
    "OT_DEBUGSERVICE_ROOT": "DebugService",
}

# ===== Libraries =====
LIBRARIES = {
    "OT_CADMODELENTITIES_ROOT": "OTCADEntities",
    "OT_DATASTORAGE_ROOT": "OTDataStorage",
    "OT_MODELENTITIES_ROOT": "OTModelEntities",
    "OT_BLOCKENTITIES_ROOT": "OTBlockEntities",
    "OT_COMMUNICATION_ROOT": "OTCommunication",
    "OT_CORE_ROOT": "OTCore",
    "OT_FOUNDATION_ROOT": "OTServiceFoundation",
    "OT_SYSTEM_ROOT": "OTSystem",
    "OT_MODELAPI_ROOT": "OTModelAPI",
    "OT_GUI_ROOT": "OTGui",
    "OT_GUIAPI_ROOT": "OTGuiAPI",
    "OT_WIDGETS_ROOT": "OTWidgets",
    "OT_FRONTEND_CONNECTOR_API_ROOT": "OTFrontendConnectorAPI",
    "OT_FILE_MANAGER_CONNECTOR_ROOT": "OTFMC",
    "OT_STUDIO_SUITE_CONNECTOR_ROOT": "OTStudioSuiteConnector",
    "OT_LTSPICE_CONNECTOR_ROOT": "OTLTSpiceConnector",
    "OT_RUBBERBANDAPI_ROOT": "OTRubberband",
    "OT_RUBBERBAND_OSG_ROOT": "OTRubberbandOSG",
    "OT_UICORE_ROOT": "uiCore",
    "OT_VIEWER_ROOT": "OTViewer",
    "OT_RESULT_DATA_ACCESS_ROOT": "OTResultDataAccess",
}

# ===== Tools =====
TOOLS = {
    "OT_OTOOLKITAPI_ROOT": "OToolkitAPI",
    "OT_OTOOLKIT_ROOT": "OToolkit",
    "OT_FILEHEADERUPDATER_ROOT": "FileHeaderUpdater",
    "OT_CONFIGMONGODBNOAUTH_ROOT": "ConfigMongoDBNoAuth",
    "OT_CONFIGMONGODBWITHAUTH_ROOT": "ConfigMongoDBWithAuth",
    "OT_ENDPOINTDOCPARSER_ROOT": "EndpointDocParser",
    "OT_GITLINECOUNTER_ROOT": "GitLineCounter",
    "OT_KEYGENERATOR_ROOT": "KeyGenerator",
    "OT_OTSYSTEMINFORMATIONTOOL_ROOT": "OTSystemInformationTool",
    "OT_PASSWORDENCRYPTION_ROOT": "PasswordEncryption",
    "OT_SETPERMISSIONS_ROOT": "SetPermissions",
    "OT_WINDOWSSSO_ROOT": "WindowsSSO",
    "OT_MONGODBUPGRADEMANAGER_ROOT": "MongoDBUpgrader/Upgrader_Exe",
}

# Each project group is resolved below the given folder of the development root.
GROUPS = ((SERVICES, "Services"), (LIBRARIES, "Libraries"), (TOOLS, "Tools"))

# ===== Relative path fragments =====
RELATIVE = {
    "OT_INC": "include",
    "OT_SRC": "src",
    "OT_CDLLD": r"build\windows-debug\Debug",
    "OT_CDLLR": r"build\windows-release\Release",
    "OT_CLIBD": r"build\windows-debug\Debug",
    "OT_CLIBR": r"build\windows-release\Release",
    "OT_TEST": "test",
}

# ===== Paths below the development root =====
DEV_PATHS = {
    "OT_ENCRYPTIONKEY_ROOT": r"Certificates\Generated",
    "OT_DOCUMENTATION_ROOT": r"Documentation\Developer",
    "OT_CMAKE_DIR": r"Scripts\CMake",
}

# ===== Certificates =====
CERTIFICATES_OVERRIDE = "OPEN_TWIN_CERTS_PATH"
CERTIFICATES_ROOT = r"Certificates\Generated"
CERTIFICATES = {
    "OPEN_TWIN_CA_CERT": "ca.pem",
    "OPEN_TWIN_CERT_KEY": "certificateKeyFile.pem",
    "OPEN_TWIN_SERVER_CERT": "server.pem",
    "OPEN_TWIN_SERVER_CERT_KEY": "server-key.pem",
}

# ===== Composite search paths =====
COMPOSITES = {
    "OT_DEFAULT_SERVICE_INCD": r"%OT_CORE_ROOT%\%OT_INC%;%OT_SYSTEM_ROOT%\%OT_INC%;%OT_GUI_ROOT%\%OT_INC%;%OT_COMMUNICATION_ROOT%\%OT_INC%;%OT_GUIAPI_ROOT%\%OT_INC%;%OT_FOUNDATION_ROOT%\%OT_INC%;%OT_MODELENTITIES_ROOT%\%OT_INC%;%OT_DATASTORAGE_ROOT%\%OT_INC%;%OT_MODELAPI_ROOT%\%OT_INC%;%R_JSON_INCD%;%CURL_INCD%;%MONGO_C_INC%;%MONGO_CXX_INC%;%MONGO_BOOST_INCD%",
    "OT_DEFAULT_SERVICE_INCR": r"%OT_CORE_ROOT%\%OT_INC%;%OT_SYSTEM_ROOT%\%OT_INC%;%OT_GUI_ROOT%\%OT_INC%;%OT_COMMUNICATION_ROOT%\%OT_INC%;%OT_GUIAPI_ROOT%\%OT_INC%;%OT_FOUNDATION_ROOT%\%OT_INC%;%OT_MODELENTITIES_ROOT%\%OT_INC%;%OT_DATASTORAGE_ROOT%\%OT_INC%;%OT_MODELAPI_ROOT%\%OT_INC%;%R_JSON_INCR%;%CURL_INCR%;%MONGO_C_INC%;%MONGO_CXX_INC%;%MONGO_BOOST_INCR%",
    "OT_DEFAULT_SERVICE_LIBPATHD": r"%OT_CORE_ROOT%\%OT_CLIBD%;%OT_SYSTEM_ROOT%\%OT_CLIBD%;%OT_GUI_ROOT%\%OT_CLIBD%;%OT_COMMUNICATION_ROOT%\%OT_CLIBD%;%OT_GUIAPI_ROOT%\%OT_CLIBD%;%OT_FOUNDATION_ROOT%\%OT_CLIBD%;%OT_MODELENTITIES_ROOT%\%OT_CLIBD%;%OT_DATASTORAGE_ROOT%\%OT_CLIBD%;%OT_MODELAPI_ROOT%\%OT_CLIBD%;%CURL_LIBPATHD%;%MONGO_C_LIBPATHD%;%MONGO_CXX_LIBPATHD%",
    "OT_DEFAULT_SERVICE_LIBPATHR": r"%OT_CORE_ROOT%\%OT_CLIBR%;%OT_SYSTEM_ROOT%\%OT_CLIBR%;%OT_GUI_ROOT%\%OT_CLIBR%;%OT_COMMUNICATION_ROOT%\%OT_CLIBR%;%OT_GUIAPI_ROOT%\%OT_CLIBR%;%OT_FOUNDATION_ROOT%\%OT_CLIBR%;%OT_MODELENTITIES_ROOT%\%OT_CLIBR%;%OT_DATASTORAGE_ROOT%\%OT_CLIBR%;%OT_MODELAPI_ROOT%\%OT_CLIBR%;%CURL_LIBPATHR%;%MONGO_C_LIBPATHR%;%MONGO_CXX_LIBPATHR%",
    "OT_DEFAULT_SERVICE_LIBD": r"OTCore.lib;OTSystem.lib;OTGui.lib;OTCommunication.lib;OTGuiAPI.lib;OTServiceFoundation.lib;OTModelEntities.lib;OTDataStorage.lib;OTModelAPI.lib;%CURL_LIBD%;%MONGO_C_LIB%;%MONGO_CXX_LIB%;%MONGO_C_LIBD%",
    "OT_DEFAULT_SERVICE_LIBR": r"OTCore.lib;OTSystem.lib;OTGui.lib;OTCommunication.lib;OTGuiAPI.lib;OTServiceFoundation.lib;OTModelEntities.lib;OTDataStorage.lib;OTModelAPI.lib;%CURL_LIBR%;%MONGO_C_LIB%;%MONGO_CXX_LIB%;%MONGO_C_LIBR%",
    "OT_DEFAULT_SERVICE_DLLD": r"%OT_CORE_ROOT%\%OT_CDLLD%;%OT_SYSTEM_ROOT%\%OT_CDLLD%;%OT_GUI_ROOT%\%OT_CDLLD%;%OT_COMMUNICATION_ROOT%\%OT_CDLLD%;%OT_GUIAPI_ROOT%\%OT_CDLLD%;%OT_FOUNDATION_ROOT%\%OT_CDLLD%;%OT_MODELENTITIES_ROOT%\%OT_CDLLD%;%OT_DATASTORAGE_ROOT%\%OT_CDLLD%;%OT_MODELAPI_ROOT%\%OT_CDLLD%;%CURL_DLLD%;%MONGO_C_DLLD%;%MONGO_CXX_DLLD%;%CURL_DLLD%;%ZLIB_DLLPATHD%;%VTK_DLLD%;%OSG_DLLD%;%QT_DLLD%;%QWT_LIB_DLLD%;%QT_TT_DLLD%",
    "OT_DEFAULT_SERVICE_DLLR": r"%OT_CORE_ROOT%\%OT_CDLLR%;%OT_SYSTEM_ROOT%\%OT_CDLLR%;%OT_GUI_ROOT%\%OT_CDLLR%;%OT_COMMUNICATION_ROOT%\%OT_CDLLR%;%OT_GUIAPI_ROOT%\%OT_CDLLR%;%OT_FOUNDATION_ROOT%\%OT_CDLLR%;%OT_MODELENTITIES_ROOT%\%OT_CDLLR%;%OT_DATASTORAGE_ROOT%\%OT_CDLLR%;%OT_MODELAPI_ROOT%\%OT_CDLLR%;%CURL_DLLR%;%MONGO_C_DLLR%;%MONGO_CXX_DLLR%;%CURL_DLLR%;%ZLIB_DLLPATHR%;%VTK_DLLR%;%OSG_DLLR%;%QT_DLLR%;%QWT_LIB_DLLR%;%QT_TT_DLLR%",
    "OT_ALL_DLLD": r"%OT_RESULT_DATA_ACCESS_ROOT%\%OT_CDLLD%;%OT_CADMODELENTITIES_ROOT%\%OT_CDLLD%;%OT_DATASTORAGE_ROOT%\%OT_CDLLD%;%OT_MODELAPI_ROOT%\%OT_CDLLD%;%OT_MODELENTITIES_ROOT%\%OT_CDLLD%;%OT_BLOCKENTITIES_ROOT%\%OT_CDLLD%;%OT_COMMUNICATION_ROOT%\%OT_CDLLD%;%OT_CORE_ROOT%\%OT_CDLLD%;%OT_GUI_ROOT%\%OT_CDLLD%;%OT_GUIAPI_ROOT%\%OT_CDLLD%;%OT_FOUNDATION_ROOT%\%OT_CDLLD%;%OT_SYSTEM_ROOT%\%OT_CDLLD%;%OT_WIDGETS_ROOT%\%OT_CDLLD%;%OT_RUBBERBANDAPI_ROOT%\%OT_CDLLD%;%OT_RUBBERBAND_OSG_ROOT%\%OT_CDLLD%;%OT_UICORE_ROOT%\%OT_CDLLD%;%OT_VIEWER_ROOT%\%OT_CDLLD%;%MONGO_C_DLLD%;%MONGO_CXX_DLLD%;%CURL_DLLD%;%ZLIB_DLLPATHD%;%VTK_DLLD%;%OSG_DLLD%;%QT_DLLD%;%QWT_LIB_DLLD%;%QT_TT_DLLD%;%OT_STUDIO_SUITE_CONNECTOR_ROOT%\%OT_CDLLD%;%OT_LTSPICE_CONNECTOR_ROOT%\%OT_CDLLD%;%OT_FRONTEND_CONNECTOR_API_ROOT%\%OT_CDLLD%;%OT_FILE_MANAGER_CONNECTOR_ROOT%\%OT_CDLLD%",
    "OT_ALL_DLLR": r"%OT_RESULT_DATA_ACCESS_ROOT%\%OT_CDLLR%;%OT_CADMODELENTITIES_ROOT%\%OT_CDLLR%;%OT_DATASTORAGE_ROOT%\%OT_CDLLR%;%OT_MODELAPI_ROOT%\%OT_CDLLR%;%OT_MODELENTITIES_ROOT%\%OT_CDLLR%;%OT_BLOCKENTITIES_ROOT%\%OT_CDLLR%;%OT_COMMUNICATION_ROOT%\%OT_CDLLR%;%OT_CORE_ROOT%\%OT_CDLLR%;%OT_GUI_ROOT%\%OT_CDLLR%;%OT_GUIAPI_ROOT%\%OT_CDLLR%;%OT_FOUNDATION_ROOT%\%OT_CDLLR%;%OT_SYSTEM_ROOT%\%OT_CDLLR%;%OT_WIDGETS_ROOT%\%OT_CDLLR%;%OT_RUBBERBANDAPI_ROOT%\%OT_CDLLR%;%OT_RUBBERBAND_OSG_ROOT%\%OT_CDLLR%;%OT_UICORE_ROOT%\%OT_CDLLR%;%OT_VIEWER_ROOT%\%OT_CDLLR%;%MONGO_C_DLLR%;%MONGO_CXX_DLLR%;%CURL_DLLR%;%ZLIB_DLLPATHR%;%VTK_DLLR%;%OSG_DLLR%;%QT_DLLR%;%QWT_LIB_DLLR%;%QT_TT_DLLR%;%OT_STUDIO_SUITE_CONNECTOR_ROOT%\%OT_CDLLR%;%OT_LTSPICE_CONNECTOR_ROOT%\%OT_CDLLR%;%OT_FRONTEND_CONNECTOR_API_ROOT%\%OT_CDLLR%;%OT_FILE_MANAGER_CONNECTOR_ROOT%\%OT_CDLLR%",
}

# Prepended to PATH in order, so the last entry ends up first.
PATH_PREPEND = [
    r"%OPENTWIN_DEV_ROOT%\Deployment",
    r"%ProgramFiles%\MiKTeX\miktex\bin\x64",
]

# ===== Externally provided environment =====
THIRDPARTY_MODULE = "SetupEnvironment.py"
SERVICE_ARGS_MODULE = ("Scripts", "Launcher", "OpenTwin_set_up_service_args.py")

READY_FLAG = "OPENTWIN_DEV_ENV_DEFINED"
