// @otlicense

#pragma once

#define OT_WIDGET_PROPERTY_TransparentBackground "OT_TransparentBackground"
#define OT_WIDGET_PROPERTY_TransparentHoverBackground "OT_TransparentHoverBackground"
#define OT_WIDGET_PROPERTY_TransparentPressedBackground "OT_TransparentPressedBackground"
#define OT_WIDGET_PROPERTY_Borderless "OT_Borderless"