@ECHO OFF

IF DEFINED OT_CERT_SETUP_COMPLETED (
	goto END
)

IF DEFINED OPEN_TWIN_CERTS_PATH (
	SET OPEN_TWIN_CA_CERT="%OPEN_TWIN_CERTS_PATH%\ca.pem"
	SET OPEN_TWIN_SERVER_CERT="%OPEN_TWIN_CERTS_PATH%\server.pem"
	SET OPEN_TWIN_SERVER_CERT_KEY="%OPEN_TWIN_CERTS_PATH%\server-key.pem"
) else (
	SET OPEN_TWIN_CA_CERT=Certificates\ca.pem
	SET OPEN_TWIN_SERVER_CERT=Certificates\server.pem
	SET OPEN_TWIN_SERVER_CERT_KEY=Certificates\server-key.pem
)

SET OT_CERT_SETUP_COMPLETED=1

:END
