name: MSBuild

on:
  push:
  pull_request:

env:
  DEVENV_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    
    - name: Check out the project repository
      uses: actions/checkout@v4
      with:
        repository: OT-OpenTwin/OpenTwin
        ref: Test
        path: OpenTwin

    - name: Check out the third-party repository
      uses: actions/checkout@v4
      with:
        repository: OT-OpenTwin/ThirdParty
        path: ThirdParty


    - name: Install Rust 1.76.0
      run: |
        choco install rust --version=1.76.0 -y
      shell: cmd

    - name: Add Visual Studio 2022
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.x'

    - name: Install Sphinx and dependencies
      run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme

    - name: Setup and Execute Build
      shell: cmd
      run: |
        echo "Current directory: %cd%"
        set OPENTWIN_DEV_ROOT=%cd%\OpenTwin
        set DEVENV_ROOT_2022=%DEVENV_PATH%
        set OPENTWIN_THIRDPARTY_ROOT=%cd%\ThirdParty
        set QtMsBuild=%cd%\OpenTwin\QtMsBuild
        echo "Starting BuildAll.bat..."
        call %OPENTWIN_DEV_ROOT%\Scripts\BuildAndTest\BuildAll.bat 

    - name: Upload build log Debug artifact
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: build-log-Debug
        path: ${{ github.workspace }}\OpenTwin\Scripts\BuildAndTest\buildLog_Debug.txt

    - name: Upload build log Release artifact
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: build-log-Release
        path: ${{ github.workspace }}\OpenTwin\Scripts\BuildAndTest\buildLog_Release.txt

    - name: Upload build log summary artifact
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: build-log-summary
        path: ${{ github.workspace }}\OpenTwin\Scripts\BuildAndTest\buildLog_Summary.txt
